import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { I18nProvider } from "./components/I18nProvider";
import { ThemeProvider } from "./components/ThemeProvider";
import LanguageSwitcher from "./components/LanguageSwitcher";
import { getRequestLocale } from "@/app/lib/i18n/server";
import type { LocaleCode } from "@/app/lib/i18n/languages";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialLocale: LocaleCode = await getRequestLocale();

  return (
    <html lang={initialLocale} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
        suppressHydrationWarning
      >
        <ThemeProvider>
          <I18nProvider initialLocale={initialLocale}>
            <LanguageSwitcher />
            {children}
          </I18nProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
